
/*
 * LinearBarGraphPanel.java
 *
 * Created on 16.01.2011, 00:52:12
 */
package core.utils.ui;

import eu.hansolo.steelseries.tools.ColorDef;

/**
 *
 * @author gmatoga
 */
public final class LinearBarGraphPanel extends javax.swing.JPanel {


    /** Creates new form LinearBarGraphPanel */
    public LinearBarGraphPanel() {
        initComponents();
        linearBargraph1.setTitle("Best fitness");
        linearBargraph1.setUnitString("Accuracy %");
        linearBargraph1.setLcdVisible(true);
        linearBargraph1.setBarGraphColor(ColorDef.JUG_GREEN);
    }

    public void setValue(double val) {
        linearBargraph1.setValue(val);
        linearBargraph1.setLcdValue(val);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linearBargraph1 = new eu.hansolo.steelseries.gauges.LinearBargraph();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(-20, -20, -20, -20));
        setLayout(new java.awt.BorderLayout());

        linearBargraph1.setBackgroundColor(eu.hansolo.steelseries.tools.BackgroundColor.LIGHT_GRAY);
        linearBargraph1.setValueColor(eu.hansolo.steelseries.tools.ColorDef.YELLOW);

        javax.swing.GroupLayout linearBargraph1Layout = new javax.swing.GroupLayout(linearBargraph1);
        linearBargraph1.setLayout(linearBargraph1Layout);
        linearBargraph1Layout.setHorizontalGroup(
            linearBargraph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        linearBargraph1Layout.setVerticalGroup(
            linearBargraph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        add(linearBargraph1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.LinearBargraph linearBargraph1;
    // End of variables declaration//GEN-END:variables
}
